[build]
  publish = "."

[functions]
  node_bundler = "esbuild"
  directory    = "netlify/functions"

[[scheduled-functions]]
  name     = "reminder"
  schedule = "0 12 * * *"

[[scheduled-functions]]
  name     = "quote-followup"
  schedule = "0 12 * * *"

[[scheduled-functions]]
  name     = "checkout-reminder"
  schedule = "0 12 * * *"
